name: DigitalBank Robot Tests

on:
  push:
    branches:
      - main      # tests sur la branche main
      - sprint_1  # tests sur la branche sprint_1 (dans l'énoncé on ne veut que dans le main)

  pull_request:
    branches:
      - main      # tests lors de PR vers main
      - sprint_1  # tests lors de PR vers sprint_1

  schedule:
    - cron: '*/5 * * * *'  # Toutes les 5 min


jobs:

  robot-tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Lancer le pipeline
      run: |
        echo "Pipeline exécutée toutes les 5 minutes"

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install robotframework
        pip install robotframework-seleniumlibrary
        pip install robotframework-jsonlibrary
        pip install robotframework-requests
        pip install selenium

    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Start Docker container
      run: |
        docker compose up -d

    - name: Wait for application
      run: |
        sleep 5

    - name: Run Robot Tests
      run: |
        robot -d reports tests/test-suites

    - name: Upload Robot Reports
      uses: actions/upload-artifact@v4
      with:
        name: robot-report
        path: reports